import { addDays, subDays } from "date-fns";
import type {
  Blocker,
  Client,
  DailyUpdate,
  Employee,
  EmployeeScore,
  GlobalDashboardData,
  Project,
  ProjectEmployee,
  ScoreHistory,
  Team,
} from "@/lib/types";

const today = new Date("2026-04-30T09:00:00.000Z");

const teams: Team[] = [
  {
    id: "team-alpha-prime",
    team_name: "Alpha Prime",
    description: "High-output delivery pod handling milestone-driven client work.",
    created_at: subDays(today, 240).toISOString(),
  },
  {
    id: "team-orbit-ops",
    team_name: "Orbit Ops",
    description: "Operations-heavy squad focused on launch support and maintenance.",
    created_at: subDays(today, 180).toISOString(),
  },
];

const employees: Employee[] = [
  { id: "emp-jihad", full_name: "Jihad Hossain", employee_code: "E-101", team_id: "team-alpha-prime", role: "employee", status: "active", created_at: subDays(today, 220).toISOString() },
  { id: "emp-mynul", full_name: "Mynul Islam", employee_code: "E-102", team_id: "team-alpha-prime", role: "team_leader", status: "active", created_at: subDays(today, 210).toISOString() },
  { id: "emp-mahadi", full_name: "Mahadi Hasan", employee_code: "E-103", team_id: "team-alpha-prime", role: "employee", status: "active", created_at: subDays(today, 180).toISOString() },
  { id: "emp-sadia", full_name: "Sadia Rahman", employee_code: "E-201", team_id: "team-orbit-ops", role: "employee", status: "active", created_at: subDays(today, 150).toISOString() },
  { id: "emp-faisal", full_name: "Faisal Ahmed", employee_code: "E-202", team_id: "team-orbit-ops", role: "employee", status: "active", created_at: subDays(today, 140).toISOString() },
];

const clients: Client[] = [
  { id: "client-northstar", client_name: "Marta Silva", company_name: "Northstar Labs", contact_info: "marta@northstarlabs.com", created_at: subDays(today, 250).toISOString() },
  { id: "client-rivermark", client_name: "Isaac Reed", company_name: "Rivermark Studio", contact_info: "isaac@rivermark.co", created_at: subDays(today, 230).toISOString() },
  { id: "client-lumen", client_name: "Rachel Kim", company_name: "Lumen Retail", contact_info: "rachel@lumenretail.com", created_at: subDays(today, 160).toISOString() },
];

const projects: Project[] = [
  {
    id: "proj-atlas",
    project_name: "Atlas Commerce Revamp",
    client_id: "client-northstar",
    order_id: "ORD-AT-8801",
    team_id: "team-alpha-prime",
    project_type: "milestone",
    total_milestones: 8,
    current_milestone: 5,
    deadline: addDays(today, 8).toISOString(),
    priority: "critical",
    risk_level: "high",
    status: "delayed",
    progress: 61,
    created_at: subDays(today, 90).toISOString(),
  },
  {
    id: "proj-pulse",
    project_name: "Pulse Analytics Suite",
    client_id: "client-rivermark",
    order_id: "ORD-PL-7720",
    team_id: "team-alpha-prime",
    project_type: "full",
    total_milestones: 6,
    current_milestone: 4,
    deadline: addDays(today, 20).toISOString(),
    priority: "high",
    risk_level: "medium",
    status: "on_track",
    progress: 73,
    created_at: subDays(today, 75).toISOString(),
  },
  {
    id: "proj-orbit",
    project_name: "Orbit Mobile Support",
    client_id: "client-lumen",
    order_id: "ORD-OR-6603",
    team_id: "team-orbit-ops",
    project_type: "milestone",
    total_milestones: 5,
    current_milestone: 5,
    deadline: addDays(today, -1).toISOString(),
    priority: "medium",
    risk_level: "low",
    status: "completed",
    progress: 100,
    created_at: subDays(today, 50).toISOString(),
  },
  {
    id: "proj-shield",
    project_name: "Shield SLA Automation",
    client_id: "client-northstar",
    order_id: "ORD-SH-9200",
    team_id: "team-orbit-ops",
    project_type: "full",
    total_milestones: 7,
    current_milestone: 2,
    deadline: addDays(today, 5).toISOString(),
    priority: "critical",
    risk_level: "critical",
    status: "blocked",
    progress: 34,
    created_at: subDays(today, 40).toISOString(),
  },
];

const projectEmployees: ProjectEmployee[] = [
  { id: "pe-1", project_id: "proj-atlas", employee_id: "emp-jihad" },
  { id: "pe-2", project_id: "proj-atlas", employee_id: "emp-mynul" },
  { id: "pe-3", project_id: "proj-pulse", employee_id: "emp-mahadi" },
  { id: "pe-4", project_id: "proj-pulse", employee_id: "emp-mynul" },
  { id: "pe-5", project_id: "proj-orbit", employee_id: "emp-sadia" },
  { id: "pe-6", project_id: "proj-shield", employee_id: "emp-faisal" },
  { id: "pe-7", project_id: "proj-shield", employee_id: "emp-sadia" },
];

const dailyUpdates = Array.from({ length: 8 }).flatMap((_, index) => {
  const day = subDays(today, 7 - index);
  const isoDay = day.toISOString();

  return [
    {
      id: `upd-jihad-${index}`,
      employee_id: "emp-jihad",
      team_id: "team-alpha-prime",
      project_id: "proj-atlas",
      client_id: "client-northstar",
      date: isoDay,
      raw_text: `Employee: Jihad Hossain\nE_ID: E-101\nClient: Northstar Labs\nProject: Atlas Commerce Revamp\nOrder ID: ORD-AT-8801\nMilestone: ${3 + Math.min(index, 2)}\nProgress: ${44 + index * 3}%\nDeadline: ${addDays(today, 8).toISOString().slice(0, 10)}\nBlockers: QA signoff delayed${index > 4 ? ", waiting on revised assets" : ""}\nNext Actions: finalize admin screens, deploy fixes\nPriority: Critical\nRisk: High\nClient Status: waiting on feedback`,
      parsed_json: {
        employee: "Jihad Hossain",
        employeeId: "E-101",
        clientName: "Northstar Labs",
        projectName: "Atlas Commerce Revamp",
        orderId: "ORD-AT-8801",
        milestone: `${3 + Math.min(index, 2)}`,
        progress: 44 + index * 3,
        deadline: addDays(today, 8).toISOString(),
        blockers: index > 4 ? ["QA signoff delayed", "Waiting on revised assets"] : ["QA signoff delayed"],
        nextActions: ["Finalize admin screens", "Deploy fixes"],
        priority: "critical",
        riskLevel: "high",
        clientStatus: "waiting on feedback",
        attachments: ["atlas-progress-sheet.png"],
      },
      progress_percentage: 44 + index * 3,
      priority: "critical",
      risk_level: "high",
      blockers: index > 4 ? ["QA signoff delayed", "Waiting on revised assets"] : ["QA signoff delayed"],
      next_actions: ["Finalize admin screens", "Deploy fixes"],
      client_status: "waiting on feedback",
      notes: "Need design approval to unlock final checkout flow.",
      quality_rating: 8,
      created_at: isoDay,
    },
    {
      id: `upd-mynul-${index}`,
      employee_id: "emp-mynul",
      team_id: "team-alpha-prime",
      project_id: index % 2 === 0 ? "proj-pulse" : "proj-atlas",
      client_id: index % 2 === 0 ? "client-rivermark" : "client-northstar",
      date: isoDay,
      raw_text: `Employee: Mynul Islam\nE_ID: E-102\nClient: ${index % 2 === 0 ? "Rivermark Studio" : "Northstar Labs"}\nProject: ${index % 2 === 0 ? "Pulse Analytics Suite" : "Atlas Commerce Revamp"}\nOrder ID: ${index % 2 === 0 ? "ORD-PL-7720" : "ORD-AT-8801"}\nMilestone: ${index % 2 === 0 ? 4 : 5}\nProgress: ${60 + index * 2}%\nDeadline: ${(index % 2 === 0 ? addDays(today, 20) : addDays(today, 8)).toISOString().slice(0, 10)}\nBlockers: none\nNext Actions: review team delivery, client follow-up\nPriority: High\nRisk: Medium\nClient Status: aligned`,
      parsed_json: {
        employee: "Mynul Islam",
        employeeId: "E-102",
        clientName: index % 2 === 0 ? "Rivermark Studio" : "Northstar Labs",
        projectName: index % 2 === 0 ? "Pulse Analytics Suite" : "Atlas Commerce Revamp",
        orderId: index % 2 === 0 ? "ORD-PL-7720" : "ORD-AT-8801",
        milestone: `${index % 2 === 0 ? 4 : 5}`,
        progress: 60 + index * 2,
        deadline: (index % 2 === 0 ? addDays(today, 20) : addDays(today, 8)).toISOString(),
        blockers: [],
        nextActions: ["Review team delivery", "Client follow-up"],
        priority: "high",
        riskLevel: "medium",
        clientStatus: "aligned",
      },
      progress_percentage: 60 + index * 2,
      priority: "high",
      risk_level: "medium",
      blockers: [],
      next_actions: ["Review team delivery", "Client follow-up"],
      client_status: "aligned",
      notes: "Cross-team support on analytics QA.",
      quality_rating: 9,
      created_at: isoDay,
    },
    ...(index === 7
      ? []
      : [
          {
            id: `upd-mahadi-${index}`,
            employee_id: "emp-mahadi",
            team_id: "team-alpha-prime",
            project_id: "proj-pulse",
            client_id: "client-rivermark",
            date: isoDay,
            raw_text: `Employee: Mahadi Hasan\nE_ID: E-103\nClient: Rivermark Studio\nProject: Pulse Analytics Suite\nOrder ID: ORD-PL-7720\nMilestone: 4\nProgress: ${48 + index * 4}%\nDeadline: ${addDays(today, 20).toISOString().slice(0, 10)}\nBlockers: API payload inconsistency\nNext Actions: normalize widgets, fix export\nPriority: High\nRisk: Medium\nClient Status: awaiting UAT`,
            parsed_json: {
              employee: "Mahadi Hasan",
              employeeId: "E-103",
              clientName: "Rivermark Studio",
              projectName: "Pulse Analytics Suite",
              orderId: "ORD-PL-7720",
              milestone: "4",
              progress: 48 + index * 4,
              deadline: addDays(today, 20).toISOString(),
              blockers: ["API payload inconsistency"],
              nextActions: ["Normalize widgets", "Fix export"],
              priority: "high",
              riskLevel: "medium",
              clientStatus: "awaiting UAT",
            },
            progress_percentage: 48 + index * 4,
            priority: "high",
            risk_level: "medium",
            blockers: ["API payload inconsistency"],
            next_actions: ["Normalize widgets", "Fix export"],
            client_status: "awaiting UAT",
            notes: "Missed today to simulate missing update tracking.",
            quality_rating: 7,
            created_at: isoDay,
          },
        ]),
    {
      id: `upd-sadia-${index}`,
      employee_id: "emp-sadia",
      team_id: "team-orbit-ops",
      project_id: index > 4 ? "proj-shield" : "proj-orbit",
      client_id: index > 4 ? "client-northstar" : "client-lumen",
      date: isoDay,
      raw_text: `Employee: Sadia Rahman\nE_ID: E-201\nClient: ${index > 4 ? "Northstar Labs" : "Lumen Retail"}\nProject: ${index > 4 ? "Shield SLA Automation" : "Orbit Mobile Support"}\nOrder ID: ${index > 4 ? "ORD-SH-9200" : "ORD-OR-6603"}\nMilestone: ${index > 4 ? 2 : 5}\nProgress: ${index > 4 ? 24 + index * 2 : 78 + index * 3}%\nDeadline: ${(index > 4 ? addDays(today, 5) : addDays(today, -1)).toISOString().slice(0, 10)}\nBlockers: ${index > 4 ? "vendor API outage" : "none"}\nNext Actions: ${index > 4 ? "retest webhook, client sync" : "handoff release notes"}\nPriority: ${index > 4 ? "Critical" : "Medium"}\nRisk: ${index > 4 ? "Critical" : "Low"}\nClient Status: ${index > 4 ? "escalated" : "done"}`,
      parsed_json: {
        employee: "Sadia Rahman",
        employeeId: "E-201",
        clientName: index > 4 ? "Northstar Labs" : "Lumen Retail",
        projectName: index > 4 ? "Shield SLA Automation" : "Orbit Mobile Support",
        orderId: index > 4 ? "ORD-SH-9200" : "ORD-OR-6603",
        milestone: `${index > 4 ? 2 : 5}`,
        progress: index > 4 ? 24 + index * 2 : 78 + index * 3,
        deadline: (index > 4 ? addDays(today, 5) : addDays(today, -1)).toISOString(),
        blockers: index > 4 ? ["Vendor API outage"] : [],
        nextActions: index > 4 ? ["Retest webhook", "Client sync"] : ["Handoff release notes"],
        priority: index > 4 ? "critical" : "medium",
        riskLevel: index > 4 ? "critical" : "low",
        clientStatus: index > 4 ? "escalated" : "done",
      },
      progress_percentage: index > 4 ? 24 + index * 2 : 78 + index * 3,
      priority: index > 4 ? "critical" : "medium",
      risk_level: index > 4 ? "critical" : "low",
      blockers: index > 4 ? ["Vendor API outage"] : [],
      next_actions: index > 4 ? ["Retest webhook", "Client sync"] : ["Handoff release notes"],
      client_status: index > 4 ? "escalated" : "done",
      notes: "Shifted focus to escalated automation issue.",
      quality_rating: 8,
      created_at: isoDay,
    },
    {
      id: `upd-faisal-${index}`,
      employee_id: "emp-faisal",
      team_id: "team-orbit-ops",
      project_id: "proj-shield",
      client_id: "client-northstar",
      date: isoDay,
      raw_text: `Employee: Faisal Ahmed\nE_ID: E-202\nClient: Northstar Labs\nProject: Shield SLA Automation\nOrder ID: ORD-SH-9200\nMilestone: 2\nProgress: ${22 + index * 2}%\nDeadline: ${addDays(today, 5).toISOString().slice(0, 10)}\nBlockers: vendor API outage, missing credentials\nNext Actions: coordinate infra, verify auth\nPriority: Critical\nRisk: Critical\nClient Status: under review`,
      parsed_json: {
        employee: "Faisal Ahmed",
        employeeId: "E-202",
        clientName: "Northstar Labs",
        projectName: "Shield SLA Automation",
        orderId: "ORD-SH-9200",
        milestone: "2",
        progress: 22 + index * 2,
        deadline: addDays(today, 5).toISOString(),
        blockers: ["Vendor API outage", "Missing credentials"],
        nextActions: ["Coordinate infra", "Verify auth"],
        priority: "critical",
        riskLevel: "critical",
        clientStatus: "under review",
      },
      progress_percentage: 22 + index * 2,
      priority: "critical",
      risk_level: "critical",
      blockers: ["Vendor API outage", "Missing credentials"],
      next_actions: ["Coordinate infra", "Verify auth"],
      client_status: "under review",
      notes: "Shared blocker repeated for scoring penalty.",
      quality_rating: 6,
      created_at: isoDay,
    },
  ];
}) as DailyUpdate[];

const blockers: Blocker[] = [
  {
    id: "blk-1",
    project_id: "proj-atlas",
    employee_id: "emp-jihad",
    team_id: "team-alpha-prime",
    description: "QA signoff delayed",
    status: "open",
    severity: "high",
    created_at: subDays(today, 4).toISOString(),
    resolved_at: null,
  },
  {
    id: "blk-2",
    project_id: "proj-shield",
    employee_id: "emp-faisal",
    team_id: "team-orbit-ops",
    description: "Vendor API outage",
    status: "open",
    severity: "critical",
    created_at: subDays(today, 3).toISOString(),
    resolved_at: null,
  },
  {
    id: "blk-3",
    project_id: "proj-shield",
    employee_id: "emp-sadia",
    team_id: "team-orbit-ops",
    description: "Missing credentials",
    status: "resolved",
    severity: "medium",
    created_at: subDays(today, 5).toISOString(),
    resolved_at: subDays(today, 2).toISOString(),
  },
];

const scores: EmployeeScore[] = [
  { id: "score-1", employee_id: "emp-jihad", team_id: "team-alpha-prime", total_score: 123, progress_score: 38, update_consistency_score: 35, blocker_resolution_score: 12, deadline_score: 11, quality_score: 16, collaboration_score: 11, last_calculated_at: today.toISOString(), created_at: subDays(today, 30).toISOString(), updated_at: today.toISOString(), trend: "up" },
  { id: "score-2", employee_id: "emp-mynul", team_id: "team-alpha-prime", total_score: 118, progress_score: 30, update_consistency_score: 34, blocker_resolution_score: 15, deadline_score: 16, quality_score: 18, collaboration_score: 5, last_calculated_at: today.toISOString(), created_at: subDays(today, 30).toISOString(), updated_at: today.toISOString(), trend: "same" },
  { id: "score-3", employee_id: "emp-mahadi", team_id: "team-alpha-prime", total_score: 87, progress_score: 26, update_consistency_score: 18, blocker_resolution_score: 9, deadline_score: 12, quality_score: 14, collaboration_score: 8, last_calculated_at: today.toISOString(), created_at: subDays(today, 30).toISOString(), updated_at: today.toISOString(), trend: "down" },
  { id: "score-4", employee_id: "emp-sadia", team_id: "team-orbit-ops", total_score: 111, progress_score: 29, update_consistency_score: 32, blocker_resolution_score: 14, deadline_score: 15, quality_score: 16, collaboration_score: 5, last_calculated_at: today.toISOString(), created_at: subDays(today, 30).toISOString(), updated_at: today.toISOString(), trend: "up" },
  { id: "score-5", employee_id: "emp-faisal", team_id: "team-orbit-ops", total_score: 76, progress_score: 19, update_consistency_score: 29, blocker_resolution_score: 6, deadline_score: 5, quality_score: 12, collaboration_score: 5, last_calculated_at: today.toISOString(), created_at: subDays(today, 30).toISOString(), updated_at: today.toISOString(), trend: "down" },
];

const scoreHistory: ScoreHistory[] = employees.flatMap((employee, employeeIndex) =>
  Array.from({ length: 6 }).map((_, index) => {
    const score = scores.find((entry) => entry.employee_id === employee.id);
    const baseline = (score?.total_score ?? 70) - 20 + index * 4 + employeeIndex;
    return {
      id: `${employee.id}-history-${index}`,
      employee_id: employee.id,
      team_id: employee.team_id,
      score_before: baseline,
      score_after: baseline + (index % 2 === 0 ? 6 : -2),
      score_change: index % 2 === 0 ? 6 : -2,
      reason: index % 2 === 0 ? "Consistent daily updates and milestone progress" : "Deadline risk and repeated blocker penalty",
      source_type: index % 3 === 0 ? "manual_adjustment" : "system_rule",
      source_id: `source-${employee.id}-${index}`,
      created_at: subDays(today, 30 - index * 5).toISOString(),
    };
  }),
);

export const demoData: GlobalDashboardData & { projectEmployees: ProjectEmployee[] } = {
  teams,
  employees,
  projects,
  updates: dailyUpdates,
  blockers,
  clients,
  scores,
  scoreHistory,
  projectEmployees,
};
